import logging
import time
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from itertools import repeat
from pprint import pprint

import yaml
from netmiko import ConnectHandler, NetMikoAuthenticationException

logging.getLogger('paramiko').setLevel(logging.WARNING) # ignore info logging level generated by module

logging.basicConfig(
    format = '%(threadName)s %(name)s %(levelname)s: %(message)s',
    level=logging.INFO)


def send_show(device_dict, command):
    start_msg = '===> {} Connection: {}'
    received_msg = '<=== {} Received:   {}'
    ip = device_dict['host']
    logging.info(start_msg.format(datetime.now().time(), ip))
    if ip == '172.16.100.130': time.sleep(5)

    try:
        with ConnectHandler(**device_dict) as ssh:
            ssh.enable()
            result = ssh.send_command(command)
            logging.info(received_msg.format(datetime.now().time(), ip))
        return result
    except NetMikoAuthenticationException as err:
        logging.warning(err)


def send_command_to_devices(devices, command):
    data = {}
    with ProcessPoolExecutor(max_workers=3) as executor:
        result = executor.map(send_show, devices, repeat(command))
        for dev, output in zip(devices, result):
            data[dev['host']] = output
    return data


if __name__ == '__main__':
    with open('devices.yaml') as f:
        devices = yaml.safe_load(f)
        # for dev in devices:
        #     pprint(send_show(dev,'sh clock')) # последовательное подключение
    pprint(send_command_to_devices(devices, 'sh ip interface'))

